/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CrossChainMessengerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "broadcast"
      | "defaultGasLimit"
      | "estimateBroadcastFee"
      | "evmToLzChainId"
      | "frostVerifier"
      | "getTrustedRemote"
      | "guardianRegistry"
      | "isEventProcessed"
      | "lzEndpoint"
      | "lzReceive"
      | "lzToEvmChainId"
      | "processedEvents"
      | "setDefaultGasLimit"
      | "setFrostVerifier"
      | "setGuardianRegistry"
      | "setTrustedRemote"
      | "trustedRemotes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "SecurityEventBroadcast"
      | "SecurityEventExecuted"
      | "SecurityEventReceived"
      | "TrustedRemoteSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "broadcast",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish[],
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultGasLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "estimateBroadcastFee",
    values: [BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "evmToLzChainId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "frostVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustedRemote",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "guardianRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isEventProcessed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lzEndpoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lzReceive",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lzToEvmChainId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processedEvents",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultGasLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFrostVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGuardianRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedRemote",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedRemotes",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "broadcast", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateBroadcastFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evmToLzChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "frostVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustedRemote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guardianRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isEventProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lzEndpoint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lzReceive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lzToEvmChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processedEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFrostVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGuardianRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedRemote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedRemotes",
    data: BytesLike
  ): Result;
}

export namespace SecurityEventBroadcastEvent {
  export type InputTuple = [
    eventId: BytesLike,
    eventType: BigNumberish,
    severity: BigNumberish,
    targetChains: BigNumberish[]
  ];
  export type OutputTuple = [
    eventId: string,
    eventType: bigint,
    severity: bigint,
    targetChains: bigint[]
  ];
  export interface OutputObject {
    eventId: string;
    eventType: bigint;
    severity: bigint;
    targetChains: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecurityEventExecutedEvent {
  export type InputTuple = [
    eventId: BytesLike,
    success: boolean,
    reason: string
  ];
  export type OutputTuple = [eventId: string, success: boolean, reason: string];
  export interface OutputObject {
    eventId: string;
    success: boolean;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecurityEventReceivedEvent {
  export type InputTuple = [
    eventId: BytesLike,
    sourceChainId: BigNumberish,
    eventType: BigNumberish,
    severity: BigNumberish
  ];
  export type OutputTuple = [
    eventId: string,
    sourceChainId: bigint,
    eventType: bigint,
    severity: bigint
  ];
  export interface OutputObject {
    eventId: string;
    sourceChainId: bigint;
    eventType: bigint;
    severity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustedRemoteSetEvent {
  export type InputTuple = [chainId: BigNumberish, path: BytesLike];
  export type OutputTuple = [chainId: bigint, path: string];
  export interface OutputObject {
    chainId: bigint;
    path: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CrossChainMessenger extends BaseContract {
  connect(runner?: ContractRunner | null): CrossChainMessenger;
  waitForDeployment(): Promise<this>;

  interface: CrossChainMessengerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  broadcast: TypedContractMethod<
    [
      eventId: BytesLike,
      eventType: BigNumberish,
      severity: BigNumberish,
      targetLzChainIds: BigNumberish[],
      actionParams: BytesLike,
      frostSignature: BytesLike,
      evidenceHash: BytesLike
    ],
    [void],
    "payable"
  >;

  defaultGasLimit: TypedContractMethod<[], [bigint], "view">;

  estimateBroadcastFee: TypedContractMethod<
    [targetLzChainIds: BigNumberish[], payload: BytesLike],
    [bigint],
    "view"
  >;

  evmToLzChainId: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  frostVerifier: TypedContractMethod<[], [string], "view">;

  getTrustedRemote: TypedContractMethod<
    [_lzChainId: BigNumberish],
    [string],
    "view"
  >;

  guardianRegistry: TypedContractMethod<[], [string], "view">;

  isEventProcessed: TypedContractMethod<
    [eventId: BytesLike],
    [boolean],
    "view"
  >;

  lzEndpoint: TypedContractMethod<[], [string], "view">;

  lzReceive: TypedContractMethod<
    [
      _srcChainId: BigNumberish,
      _srcAddress: BytesLike,
      _nonce: BigNumberish,
      _payload: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  lzToEvmChainId: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  processedEvents: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  setDefaultGasLimit: TypedContractMethod<
    [_gasLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFrostVerifier: TypedContractMethod<
    [_frostVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  setGuardianRegistry: TypedContractMethod<
    [_guardianRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  setTrustedRemote: TypedContractMethod<
    [_lzChainId: BigNumberish, _path: BytesLike],
    [void],
    "nonpayable"
  >;

  trustedRemotes: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "broadcast"
  ): TypedContractMethod<
    [
      eventId: BytesLike,
      eventType: BigNumberish,
      severity: BigNumberish,
      targetLzChainIds: BigNumberish[],
      actionParams: BytesLike,
      frostSignature: BytesLike,
      evidenceHash: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "defaultGasLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "estimateBroadcastFee"
  ): TypedContractMethod<
    [targetLzChainIds: BigNumberish[], payload: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "evmToLzChainId"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "frostVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTrustedRemote"
  ): TypedContractMethod<[_lzChainId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "guardianRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isEventProcessed"
  ): TypedContractMethod<[eventId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lzEndpoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lzReceive"
  ): TypedContractMethod<
    [
      _srcChainId: BigNumberish,
      _srcAddress: BytesLike,
      _nonce: BigNumberish,
      _payload: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lzToEvmChainId"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "processedEvents"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setDefaultGasLimit"
  ): TypedContractMethod<[_gasLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFrostVerifier"
  ): TypedContractMethod<[_frostVerifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGuardianRegistry"
  ): TypedContractMethod<
    [_guardianRegistry: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTrustedRemote"
  ): TypedContractMethod<
    [_lzChainId: BigNumberish, _path: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "trustedRemotes"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "SecurityEventBroadcast"
  ): TypedContractEvent<
    SecurityEventBroadcastEvent.InputTuple,
    SecurityEventBroadcastEvent.OutputTuple,
    SecurityEventBroadcastEvent.OutputObject
  >;
  getEvent(
    key: "SecurityEventExecuted"
  ): TypedContractEvent<
    SecurityEventExecutedEvent.InputTuple,
    SecurityEventExecutedEvent.OutputTuple,
    SecurityEventExecutedEvent.OutputObject
  >;
  getEvent(
    key: "SecurityEventReceived"
  ): TypedContractEvent<
    SecurityEventReceivedEvent.InputTuple,
    SecurityEventReceivedEvent.OutputTuple,
    SecurityEventReceivedEvent.OutputObject
  >;
  getEvent(
    key: "TrustedRemoteSet"
  ): TypedContractEvent<
    TrustedRemoteSetEvent.InputTuple,
    TrustedRemoteSetEvent.OutputTuple,
    TrustedRemoteSetEvent.OutputObject
  >;

  filters: {
    "SecurityEventBroadcast(bytes32,uint8,uint8,uint16[])": TypedContractEvent<
      SecurityEventBroadcastEvent.InputTuple,
      SecurityEventBroadcastEvent.OutputTuple,
      SecurityEventBroadcastEvent.OutputObject
    >;
    SecurityEventBroadcast: TypedContractEvent<
      SecurityEventBroadcastEvent.InputTuple,
      SecurityEventBroadcastEvent.OutputTuple,
      SecurityEventBroadcastEvent.OutputObject
    >;

    "SecurityEventExecuted(bytes32,bool,string)": TypedContractEvent<
      SecurityEventExecutedEvent.InputTuple,
      SecurityEventExecutedEvent.OutputTuple,
      SecurityEventExecutedEvent.OutputObject
    >;
    SecurityEventExecuted: TypedContractEvent<
      SecurityEventExecutedEvent.InputTuple,
      SecurityEventExecutedEvent.OutputTuple,
      SecurityEventExecutedEvent.OutputObject
    >;

    "SecurityEventReceived(bytes32,uint16,uint8,uint8)": TypedContractEvent<
      SecurityEventReceivedEvent.InputTuple,
      SecurityEventReceivedEvent.OutputTuple,
      SecurityEventReceivedEvent.OutputObject
    >;
    SecurityEventReceived: TypedContractEvent<
      SecurityEventReceivedEvent.InputTuple,
      SecurityEventReceivedEvent.OutputTuple,
      SecurityEventReceivedEvent.OutputObject
    >;

    "TrustedRemoteSet(uint16,bytes)": TypedContractEvent<
      TrustedRemoteSetEvent.InputTuple,
      TrustedRemoteSetEvent.OutputTuple,
      TrustedRemoteSetEvent.OutputObject
    >;
    TrustedRemoteSet: TypedContractEvent<
      TrustedRemoteSetEvent.InputTuple,
      TrustedRemoteSetEvent.OutputTuple,
      TrustedRemoteSetEvent.OutputObject
    >;
  };
}
