/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FROSTVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_POINT"
      | "getGroupPublicKey"
      | "groupPublicKey"
      | "guardianRegistry"
      | "updateGroupPublicKey"
      | "verify"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "GroupPublicKeyUpdated" | "SignatureVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_POINT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGroupPublicKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "groupPublicKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "guardianRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateGroupPublicKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "BASE_POINT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGroupPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "groupPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guardianRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGroupPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace GroupPublicKeyUpdatedEvent {
  export type InputTuple = [oldKey: BytesLike, newKey: BytesLike];
  export type OutputTuple = [oldKey: string, newKey: string];
  export interface OutputObject {
    oldKey: string;
    newKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignatureVerifiedEvent {
  export type InputTuple = [messageHash: BytesLike, valid: boolean];
  export type OutputTuple = [messageHash: string, valid: boolean];
  export interface OutputObject {
    messageHash: string;
    valid: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FROSTVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): FROSTVerifier;
  waitForDeployment(): Promise<this>;

  interface: FROSTVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_POINT: TypedContractMethod<[], [string], "view">;

  getGroupPublicKey: TypedContractMethod<[], [string], "view">;

  groupPublicKey: TypedContractMethod<[], [string], "view">;

  guardianRegistry: TypedContractMethod<[], [string], "view">;

  updateGroupPublicKey: TypedContractMethod<
    [newGroupPublicKey: BytesLike],
    [void],
    "nonpayable"
  >;

  verify: TypedContractMethod<
    [message: BytesLike, R: BytesLike, z: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_POINT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getGroupPublicKey"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "groupPublicKey"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "guardianRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateGroupPublicKey"
  ): TypedContractMethod<[newGroupPublicKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [message: BytesLike, R: BytesLike, z: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "GroupPublicKeyUpdated"
  ): TypedContractEvent<
    GroupPublicKeyUpdatedEvent.InputTuple,
    GroupPublicKeyUpdatedEvent.OutputTuple,
    GroupPublicKeyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SignatureVerified"
  ): TypedContractEvent<
    SignatureVerifiedEvent.InputTuple,
    SignatureVerifiedEvent.OutputTuple,
    SignatureVerifiedEvent.OutputObject
  >;

  filters: {
    "GroupPublicKeyUpdated(bytes32,bytes32)": TypedContractEvent<
      GroupPublicKeyUpdatedEvent.InputTuple,
      GroupPublicKeyUpdatedEvent.OutputTuple,
      GroupPublicKeyUpdatedEvent.OutputObject
    >;
    GroupPublicKeyUpdated: TypedContractEvent<
      GroupPublicKeyUpdatedEvent.InputTuple,
      GroupPublicKeyUpdatedEvent.OutputTuple,
      GroupPublicKeyUpdatedEvent.OutputObject
    >;

    "SignatureVerified(bytes32,bool)": TypedContractEvent<
      SignatureVerifiedEvent.InputTuple,
      SignatureVerifiedEvent.OutputTuple,
      SignatureVerifiedEvent.OutputObject
    >;
    SignatureVerified: TypedContractEvent<
      SignatureVerifiedEvent.InputTuple,
      SignatureVerifiedEvent.OutputTuple,
      SignatureVerifiedEvent.OutputObject
    >;
  };
}
