/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface VDFVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ITERATIONS"
      | "MAX_ITERATIONS"
      | "RSA_2048_BYTES"
      | "SQUARINGS_PER_SECOND"
      | "getDefaultParams"
      | "getExpectedTime"
      | "verify"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "VDFProofRejected" | "VDFVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ITERATIONS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_ITERATIONS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RSA_2048_BYTES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SQUARINGS_PER_SECOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDefaultParams",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExpectedTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ITERATIONS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_ITERATIONS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RSA_2048_BYTES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SQUARINGS_PER_SECOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDefaultParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpectedTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace VDFProofRejectedEvent {
  export type InputTuple = [txHash: BytesLike, reason: string];
  export type OutputTuple = [txHash: string, reason: string];
  export interface OutputObject {
    txHash: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VDFVerifiedEvent {
  export type InputTuple = [txHash: BytesLike, valid: boolean];
  export type OutputTuple = [txHash: string, valid: boolean];
  export interface OutputObject {
    txHash: string;
    valid: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VDFVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): VDFVerifier;
  waitForDeployment(): Promise<this>;

  interface: VDFVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ITERATIONS: TypedContractMethod<[], [bigint], "view">;

  MAX_ITERATIONS: TypedContractMethod<[], [bigint], "view">;

  RSA_2048_BYTES: TypedContractMethod<[], [bigint], "view">;

  SQUARINGS_PER_SECOND: TypedContractMethod<[], [bigint], "view">;

  getDefaultParams: TypedContractMethod<
    [],
    [[bigint, bigint] & { iterations: bigint; delaySeconds: bigint }],
    "view"
  >;

  getExpectedTime: TypedContractMethod<
    [iterations: BigNumberish],
    [bigint],
    "view"
  >;

  verify: TypedContractMethod<
    [txHash: BytesLike, startTime: BigNumberish, proof: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ITERATIONS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_ITERATIONS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RSA_2048_BYTES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SQUARINGS_PER_SECOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDefaultParams"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { iterations: bigint; delaySeconds: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getExpectedTime"
  ): TypedContractMethod<[iterations: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [txHash: BytesLike, startTime: BigNumberish, proof: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "VDFProofRejected"
  ): TypedContractEvent<
    VDFProofRejectedEvent.InputTuple,
    VDFProofRejectedEvent.OutputTuple,
    VDFProofRejectedEvent.OutputObject
  >;
  getEvent(
    key: "VDFVerified"
  ): TypedContractEvent<
    VDFVerifiedEvent.InputTuple,
    VDFVerifiedEvent.OutputTuple,
    VDFVerifiedEvent.OutputObject
  >;

  filters: {
    "VDFProofRejected(bytes32,string)": TypedContractEvent<
      VDFProofRejectedEvent.InputTuple,
      VDFProofRejectedEvent.OutputTuple,
      VDFProofRejectedEvent.OutputObject
    >;
    VDFProofRejected: TypedContractEvent<
      VDFProofRejectedEvent.InputTuple,
      VDFProofRejectedEvent.OutputTuple,
      VDFProofRejectedEvent.OutputObject
    >;

    "VDFVerified(bytes32,bool)": TypedContractEvent<
      VDFVerifiedEvent.InputTuple,
      VDFVerifiedEvent.OutputTuple,
      VDFVerifiedEvent.OutputObject
    >;
    VDFVerified: TypedContractEvent<
      VDFVerifiedEvent.InputTuple,
      VDFVerifiedEvent.OutputTuple,
      VDFVerifiedEvent.OutputObject
    >;
  };
}
