/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ZKVoteVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COMMIT_PHASE_DURATION"
      | "createProposal"
      | "getCommitDeadline"
      | "getProposalState"
      | "guardianAddresses"
      | "guardianPubKeys"
      | "guardianRegistry"
      | "isCommitted"
      | "proposalExists"
      | "proposals"
      | "revealVote"
      | "submitCommitment"
      | "threshold"
      | "verifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CommitmentSubmitted"
      | "ProposalCreated"
      | "ProposalFinalized"
      | "VoteRevealed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COMMIT_PHASE_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitDeadline",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalState",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "guardianAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "guardianPubKeys",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "guardianRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isCommitted",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revealVote",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "submitCommitment",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "threshold", values?: undefined): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "COMMIT_PHASE_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommitDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guardianAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guardianPubKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guardianRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCommitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revealVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "threshold", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
}

export namespace CommitmentSubmittedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    guardianSlot: BigNumberish,
    commitment: BytesLike
  ];
  export type OutputTuple = [
    proposalId: string,
    guardianSlot: bigint,
    commitment: string
  ];
  export interface OutputObject {
    proposalId: string;
    guardianSlot: bigint;
    commitment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    commitDeadline: BigNumberish,
    description: string
  ];
  export type OutputTuple = [
    proposalId: string,
    commitDeadline: bigint,
    description: string
  ];
  export interface OutputObject {
    proposalId: string;
    commitDeadline: bigint;
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalFinalizedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    approvals: BigNumberish,
    rejections: BigNumberish,
    abstentions: BigNumberish,
    passed: boolean
  ];
  export type OutputTuple = [
    proposalId: string,
    approvals: bigint,
    rejections: bigint,
    abstentions: bigint,
    passed: boolean
  ];
  export interface OutputObject {
    proposalId: string;
    approvals: bigint;
    rejections: bigint;
    abstentions: bigint;
    passed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteRevealedEvent {
  export type InputTuple = [proposalId: BytesLike, vote: BigNumberish];
  export type OutputTuple = [proposalId: string, vote: bigint];
  export interface OutputObject {
    proposalId: string;
    vote: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ZKVoteVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): ZKVoteVerifier;
  waitForDeployment(): Promise<this>;

  interface: ZKVoteVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COMMIT_PHASE_DURATION: TypedContractMethod<[], [bigint], "view">;

  createProposal: TypedContractMethod<
    [proposalId: BytesLike, description: string],
    [void],
    "nonpayable"
  >;

  getCommitDeadline: TypedContractMethod<
    [proposalId: BytesLike],
    [bigint],
    "view"
  >;

  getProposalState: TypedContractMethod<
    [proposalId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        commitCount: bigint;
        revealCount: bigint;
        approveCount: bigint;
        rejectCount: bigint;
        abstainCount: bigint;
        isFinalized: boolean;
      }
    ],
    "view"
  >;

  guardianAddresses: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  guardianPubKeys: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  guardianRegistry: TypedContractMethod<[], [string], "view">;

  isCommitted: TypedContractMethod<
    [proposalId: BytesLike, guardianSlot: BigNumberish],
    [boolean],
    "view"
  >;

  proposalExists: TypedContractMethod<
    [proposalId: BytesLike],
    [boolean],
    "view"
  >;

  proposals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint, boolean] & {
        commitCount: bigint;
        approvals: bigint;
        rejections: bigint;
        abstentions: bigint;
        revealCount: bigint;
        finalized: boolean;
        commitDeadline: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  revealVote: TypedContractMethod<
    [
      proposalId: BytesLike,
      guardianSlot: BigNumberish,
      vote: BigNumberish,
      pA: [BigNumberish, BigNumberish],
      pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      pC: [BigNumberish, BigNumberish]
    ],
    [void],
    "nonpayable"
  >;

  submitCommitment: TypedContractMethod<
    [proposalId: BytesLike, commitment: BytesLike, guardianSlot: BigNumberish],
    [void],
    "nonpayable"
  >;

  threshold: TypedContractMethod<[], [bigint], "view">;

  verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COMMIT_PHASE_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [proposalId: BytesLike, description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCommitDeadline"
  ): TypedContractMethod<[proposalId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProposalState"
  ): TypedContractMethod<
    [proposalId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        commitCount: bigint;
        revealCount: bigint;
        approveCount: bigint;
        rejectCount: bigint;
        abstainCount: bigint;
        isFinalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "guardianAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "guardianPubKeys"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "guardianRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isCommitted"
  ): TypedContractMethod<
    [proposalId: BytesLike, guardianSlot: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposalExists"
  ): TypedContractMethod<[proposalId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint, boolean] & {
        commitCount: bigint;
        approvals: bigint;
        rejections: bigint;
        abstentions: bigint;
        revealCount: bigint;
        finalized: boolean;
        commitDeadline: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revealVote"
  ): TypedContractMethod<
    [
      proposalId: BytesLike,
      guardianSlot: BigNumberish,
      vote: BigNumberish,
      pA: [BigNumberish, BigNumberish],
      pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      pC: [BigNumberish, BigNumberish]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitCommitment"
  ): TypedContractMethod<
    [proposalId: BytesLike, commitment: BytesLike, guardianSlot: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "threshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CommitmentSubmitted"
  ): TypedContractEvent<
    CommitmentSubmittedEvent.InputTuple,
    CommitmentSubmittedEvent.OutputTuple,
    CommitmentSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalFinalized"
  ): TypedContractEvent<
    ProposalFinalizedEvent.InputTuple,
    ProposalFinalizedEvent.OutputTuple,
    ProposalFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "VoteRevealed"
  ): TypedContractEvent<
    VoteRevealedEvent.InputTuple,
    VoteRevealedEvent.OutputTuple,
    VoteRevealedEvent.OutputObject
  >;

  filters: {
    "CommitmentSubmitted(bytes32,uint8,bytes32)": TypedContractEvent<
      CommitmentSubmittedEvent.InputTuple,
      CommitmentSubmittedEvent.OutputTuple,
      CommitmentSubmittedEvent.OutputObject
    >;
    CommitmentSubmitted: TypedContractEvent<
      CommitmentSubmittedEvent.InputTuple,
      CommitmentSubmittedEvent.OutputTuple,
      CommitmentSubmittedEvent.OutputObject
    >;

    "ProposalCreated(bytes32,uint256,string)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalFinalized(bytes32,uint8,uint8,uint8,bool)": TypedContractEvent<
      ProposalFinalizedEvent.InputTuple,
      ProposalFinalizedEvent.OutputTuple,
      ProposalFinalizedEvent.OutputObject
    >;
    ProposalFinalized: TypedContractEvent<
      ProposalFinalizedEvent.InputTuple,
      ProposalFinalizedEvent.OutputTuple,
      ProposalFinalizedEvent.OutputObject
    >;

    "VoteRevealed(bytes32,uint8)": TypedContractEvent<
      VoteRevealedEvent.InputTuple,
      VoteRevealedEvent.OutputTuple,
      VoteRevealedEvent.OutputObject
    >;
    VoteRevealed: TypedContractEvent<
      VoteRevealedEvent.InputTuple,
      VoteRevealedEvent.OutputTuple,
      VoteRevealedEvent.OutputObject
    >;
  };
}
