/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iLayerZeroEndpointSol from "./ILayerZeroEndpoint.sol";
export type { iLayerZeroEndpointSol };
