/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GuardianRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "blacklistedAddresses"
      | "crossChainMessenger"
      | "currentThreshold"
      | "emergencyPause"
      | "executeProposal"
      | "frostVerifier"
      | "getProposalDetails"
      | "getSecurityState"
      | "initiateVote"
      | "isBlacklisted"
      | "isCrossChainEventProcessed"
      | "isPaused"
      | "owner"
      | "processedCrossChainEvents"
      | "processedProposals"
      | "proposals"
      | "receiveRemoteBlacklist"
      | "receiveRemoteMonitor"
      | "receiveRemotePause"
      | "receiveRemoteThresholdIncrease"
      | "receiveRemoteUnblacklist"
      | "receiveRemoteUnpause"
      | "setCrossChainMessenger"
      | "zkVoteVerifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressBlacklisted"
      | "AddressUnblacklisted"
      | "CrossChainEventReceived"
      | "CrossChainMessengerUpdated"
      | "FROSTSigningRequired"
      | "Paused"
      | "ProposalInitiated"
      | "SecurityActionExecuted"
      | "ThresholdIncreased"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "blacklistedAddresses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "crossChainMessenger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "frostVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalDetails",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSecurityState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initiateVote",
    values: [BytesLike, BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCrossChainEventProcessed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processedCrossChainEvents",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processedProposals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveRemoteBlacklist",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveRemoteMonitor",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveRemotePause",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveRemoteThresholdIncrease",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveRemoteUnblacklist",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveRemoteUnpause",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCrossChainMessenger",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "zkVoteVerifier",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "blacklistedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "crossChainMessenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "frostVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSecurityState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCrossChainEventProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processedCrossChainEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processedProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveRemoteBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveRemoteMonitor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveRemotePause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveRemoteThresholdIncrease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveRemoteUnblacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveRemoteUnpause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCrossChainMessenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "zkVoteVerifier",
    data: BytesLike
  ): Result;
}

export namespace AddressBlacklistedEvent {
  export type InputTuple = [target: AddressLike, eventId: BytesLike];
  export type OutputTuple = [target: string, eventId: string];
  export interface OutputObject {
    target: string;
    eventId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddressUnblacklistedEvent {
  export type InputTuple = [target: AddressLike, eventId: BytesLike];
  export type OutputTuple = [target: string, eventId: string];
  export interface OutputObject {
    target: string;
    eventId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainEventReceivedEvent {
  export type InputTuple = [
    eventId: BytesLike,
    sourceChain: BigNumberish,
    action: BigNumberish
  ];
  export type OutputTuple = [
    eventId: string,
    sourceChain: bigint,
    action: bigint
  ];
  export interface OutputObject {
    eventId: string;
    sourceChain: bigint;
    action: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainMessengerUpdatedEvent {
  export type InputTuple = [
    oldMessenger: AddressLike,
    newMessenger: AddressLike
  ];
  export type OutputTuple = [oldMessenger: string, newMessenger: string];
  export interface OutputObject {
    oldMessenger: string;
    newMessenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FROSTSigningRequiredEvent {
  export type InputTuple = [proposalId: BytesLike, action: BigNumberish];
  export type OutputTuple = [proposalId: string, action: bigint];
  export interface OutputObject {
    proposalId: string;
    action: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [eventId: BytesLike, reason: string];
  export type OutputTuple = [eventId: string, reason: string];
  export interface OutputObject {
    eventId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalInitiatedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    action: BigNumberish,
    description: string
  ];
  export type OutputTuple = [
    proposalId: string,
    action: bigint,
    description: string
  ];
  export interface OutputObject {
    proposalId: string;
    action: bigint;
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecurityActionExecutedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    action: BigNumberish,
    success: boolean
  ];
  export type OutputTuple = [
    proposalId: string,
    action: bigint,
    success: boolean
  ];
  export interface OutputObject {
    proposalId: string;
    action: bigint;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdIncreasedEvent {
  export type InputTuple = [
    oldThreshold: BigNumberish,
    newThreshold: BigNumberish,
    eventId: BytesLike
  ];
  export type OutputTuple = [
    oldThreshold: bigint,
    newThreshold: bigint,
    eventId: string
  ];
  export interface OutputObject {
    oldThreshold: bigint;
    newThreshold: bigint;
    eventId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [eventId: BytesLike];
  export type OutputTuple = [eventId: string];
  export interface OutputObject {
    eventId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GuardianRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): GuardianRegistry;
  waitForDeployment(): Promise<this>;

  interface: GuardianRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  blacklistedAddresses: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  crossChainMessenger: TypedContractMethod<[], [string], "view">;

  currentThreshold: TypedContractMethod<[], [bigint], "view">;

  emergencyPause: TypedContractMethod<
    [eventId: BytesLike, frostSignature: BytesLike],
    [void],
    "nonpayable"
  >;

  executeProposal: TypedContractMethod<
    [proposalId: BytesLike, frostSignature: BytesLike],
    [void],
    "nonpayable"
  >;

  frostVerifier: TypedContractMethod<[], [string], "view">;

  getProposalDetails: TypedContractMethod<
    [proposalId: BytesLike],
    [
      [bigint, string, string, boolean] & {
        action: bigint;
        targetAddress: string;
        description: string;
        executed: boolean;
      }
    ],
    "view"
  >;

  getSecurityState: TypedContractMethod<
    [],
    [
      [boolean, bigint, bigint] & {
        paused: boolean;
        threshold: bigint;
        proposalCount: bigint;
      }
    ],
    "view"
  >;

  initiateVote: TypedContractMethod<
    [
      proposalId: BytesLike,
      action: BigNumberish,
      targetAddress: AddressLike,
      description: string
    ],
    [void],
    "nonpayable"
  >;

  isBlacklisted: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  isCrossChainEventProcessed: TypedContractMethod<
    [eventId: BytesLike],
    [boolean],
    "view"
  >;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  processedCrossChainEvents: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  processedProposals: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  proposals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, string, boolean] & {
        action: bigint;
        targetAddress: string;
        description: string;
        executed: boolean;
      }
    ],
    "view"
  >;

  receiveRemoteBlacklist: TypedContractMethod<
    [eventId: BytesLike, sourceChain: BigNumberish, target: AddressLike],
    [void],
    "nonpayable"
  >;

  receiveRemoteMonitor: TypedContractMethod<
    [eventId: BytesLike, sourceChain: BigNumberish],
    [void],
    "nonpayable"
  >;

  receiveRemotePause: TypedContractMethod<
    [eventId: BytesLike, sourceChain: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  receiveRemoteThresholdIncrease: TypedContractMethod<
    [eventId: BytesLike, sourceChain: BigNumberish],
    [void],
    "nonpayable"
  >;

  receiveRemoteUnblacklist: TypedContractMethod<
    [eventId: BytesLike, sourceChain: BigNumberish, target: AddressLike],
    [void],
    "nonpayable"
  >;

  receiveRemoteUnpause: TypedContractMethod<
    [eventId: BytesLike, sourceChain: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCrossChainMessenger: TypedContractMethod<
    [_messenger: AddressLike],
    [void],
    "nonpayable"
  >;

  zkVoteVerifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "blacklistedAddresses"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "crossChainMessenger"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currentThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<
    [eventId: BytesLike, frostSignature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeProposal"
  ): TypedContractMethod<
    [proposalId: BytesLike, frostSignature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "frostVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getProposalDetails"
  ): TypedContractMethod<
    [proposalId: BytesLike],
    [
      [bigint, string, string, boolean] & {
        action: bigint;
        targetAddress: string;
        description: string;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSecurityState"
  ): TypedContractMethod<
    [],
    [
      [boolean, bigint, bigint] & {
        paused: boolean;
        threshold: bigint;
        proposalCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initiateVote"
  ): TypedContractMethod<
    [
      proposalId: BytesLike,
      action: BigNumberish,
      targetAddress: AddressLike,
      description: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isBlacklisted"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isCrossChainEventProcessed"
  ): TypedContractMethod<[eventId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processedCrossChainEvents"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "processedProposals"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, string, boolean] & {
        action: bigint;
        targetAddress: string;
        description: string;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "receiveRemoteBlacklist"
  ): TypedContractMethod<
    [eventId: BytesLike, sourceChain: BigNumberish, target: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "receiveRemoteMonitor"
  ): TypedContractMethod<
    [eventId: BytesLike, sourceChain: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "receiveRemotePause"
  ): TypedContractMethod<
    [eventId: BytesLike, sourceChain: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "receiveRemoteThresholdIncrease"
  ): TypedContractMethod<
    [eventId: BytesLike, sourceChain: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "receiveRemoteUnblacklist"
  ): TypedContractMethod<
    [eventId: BytesLike, sourceChain: BigNumberish, target: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "receiveRemoteUnpause"
  ): TypedContractMethod<
    [eventId: BytesLike, sourceChain: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCrossChainMessenger"
  ): TypedContractMethod<[_messenger: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "zkVoteVerifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AddressBlacklisted"
  ): TypedContractEvent<
    AddressBlacklistedEvent.InputTuple,
    AddressBlacklistedEvent.OutputTuple,
    AddressBlacklistedEvent.OutputObject
  >;
  getEvent(
    key: "AddressUnblacklisted"
  ): TypedContractEvent<
    AddressUnblacklistedEvent.InputTuple,
    AddressUnblacklistedEvent.OutputTuple,
    AddressUnblacklistedEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainEventReceived"
  ): TypedContractEvent<
    CrossChainEventReceivedEvent.InputTuple,
    CrossChainEventReceivedEvent.OutputTuple,
    CrossChainEventReceivedEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainMessengerUpdated"
  ): TypedContractEvent<
    CrossChainMessengerUpdatedEvent.InputTuple,
    CrossChainMessengerUpdatedEvent.OutputTuple,
    CrossChainMessengerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FROSTSigningRequired"
  ): TypedContractEvent<
    FROSTSigningRequiredEvent.InputTuple,
    FROSTSigningRequiredEvent.OutputTuple,
    FROSTSigningRequiredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalInitiated"
  ): TypedContractEvent<
    ProposalInitiatedEvent.InputTuple,
    ProposalInitiatedEvent.OutputTuple,
    ProposalInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "SecurityActionExecuted"
  ): TypedContractEvent<
    SecurityActionExecutedEvent.InputTuple,
    SecurityActionExecutedEvent.OutputTuple,
    SecurityActionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdIncreased"
  ): TypedContractEvent<
    ThresholdIncreasedEvent.InputTuple,
    ThresholdIncreasedEvent.OutputTuple,
    ThresholdIncreasedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AddressBlacklisted(address,bytes32)": TypedContractEvent<
      AddressBlacklistedEvent.InputTuple,
      AddressBlacklistedEvent.OutputTuple,
      AddressBlacklistedEvent.OutputObject
    >;
    AddressBlacklisted: TypedContractEvent<
      AddressBlacklistedEvent.InputTuple,
      AddressBlacklistedEvent.OutputTuple,
      AddressBlacklistedEvent.OutputObject
    >;

    "AddressUnblacklisted(address,bytes32)": TypedContractEvent<
      AddressUnblacklistedEvent.InputTuple,
      AddressUnblacklistedEvent.OutputTuple,
      AddressUnblacklistedEvent.OutputObject
    >;
    AddressUnblacklisted: TypedContractEvent<
      AddressUnblacklistedEvent.InputTuple,
      AddressUnblacklistedEvent.OutputTuple,
      AddressUnblacklistedEvent.OutputObject
    >;

    "CrossChainEventReceived(bytes32,uint16,uint8)": TypedContractEvent<
      CrossChainEventReceivedEvent.InputTuple,
      CrossChainEventReceivedEvent.OutputTuple,
      CrossChainEventReceivedEvent.OutputObject
    >;
    CrossChainEventReceived: TypedContractEvent<
      CrossChainEventReceivedEvent.InputTuple,
      CrossChainEventReceivedEvent.OutputTuple,
      CrossChainEventReceivedEvent.OutputObject
    >;

    "CrossChainMessengerUpdated(address,address)": TypedContractEvent<
      CrossChainMessengerUpdatedEvent.InputTuple,
      CrossChainMessengerUpdatedEvent.OutputTuple,
      CrossChainMessengerUpdatedEvent.OutputObject
    >;
    CrossChainMessengerUpdated: TypedContractEvent<
      CrossChainMessengerUpdatedEvent.InputTuple,
      CrossChainMessengerUpdatedEvent.OutputTuple,
      CrossChainMessengerUpdatedEvent.OutputObject
    >;

    "FROSTSigningRequired(bytes32,uint8)": TypedContractEvent<
      FROSTSigningRequiredEvent.InputTuple,
      FROSTSigningRequiredEvent.OutputTuple,
      FROSTSigningRequiredEvent.OutputObject
    >;
    FROSTSigningRequired: TypedContractEvent<
      FROSTSigningRequiredEvent.InputTuple,
      FROSTSigningRequiredEvent.OutputTuple,
      FROSTSigningRequiredEvent.OutputObject
    >;

    "Paused(bytes32,string)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProposalInitiated(bytes32,uint8,string)": TypedContractEvent<
      ProposalInitiatedEvent.InputTuple,
      ProposalInitiatedEvent.OutputTuple,
      ProposalInitiatedEvent.OutputObject
    >;
    ProposalInitiated: TypedContractEvent<
      ProposalInitiatedEvent.InputTuple,
      ProposalInitiatedEvent.OutputTuple,
      ProposalInitiatedEvent.OutputObject
    >;

    "SecurityActionExecuted(bytes32,uint8,bool)": TypedContractEvent<
      SecurityActionExecutedEvent.InputTuple,
      SecurityActionExecutedEvent.OutputTuple,
      SecurityActionExecutedEvent.OutputObject
    >;
    SecurityActionExecuted: TypedContractEvent<
      SecurityActionExecutedEvent.InputTuple,
      SecurityActionExecutedEvent.OutputTuple,
      SecurityActionExecutedEvent.OutputObject
    >;

    "ThresholdIncreased(uint8,uint8,bytes32)": TypedContractEvent<
      ThresholdIncreasedEvent.InputTuple,
      ThresholdIncreasedEvent.OutputTuple,
      ThresholdIncreasedEvent.OutputObject
    >;
    ThresholdIncreased: TypedContractEvent<
      ThresholdIncreasedEvent.InputTuple,
      ThresholdIncreasedEvent.OutputTuple,
      ThresholdIncreasedEvent.OutputObject
    >;

    "Unpaused(bytes32)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
