/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IZKVoteVerifierInterface extends Interface {
  getFunction(
    nameOrSignature: "createProposal" | "getProposalState"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createProposal",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalState",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalState",
    data: BytesLike
  ): Result;
}

export interface IZKVoteVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): IZKVoteVerifier;
  waitForDeployment(): Promise<this>;

  interface: IZKVoteVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createProposal: TypedContractMethod<
    [proposalId: BytesLike, description: string],
    [void],
    "nonpayable"
  >;

  getProposalState: TypedContractMethod<
    [proposalId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        commitCount: bigint;
        revealCount: bigint;
        approvals: bigint;
        rejections: bigint;
        abstentions: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [proposalId: BytesLike, description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getProposalState"
  ): TypedContractMethod<
    [proposalId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        commitCount: bigint;
        revealCount: bigint;
        approvals: bigint;
        rejections: bigint;
        abstentions: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;

  filters: {};
}
