/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFROSTVerifier,
  IFROSTVerifierInterface,
} from "../../SecurityMiddleware.sol/IFROSTVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "message",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "R",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "z",
        type: "bytes32",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFROSTVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IFROSTVerifierInterface {
    return new Interface(_abi) as IFROSTVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFROSTVerifier {
    return new Contract(address, _abi, runner) as unknown as IFROSTVerifier;
  }
}
