/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVDFVerifier,
  IVDFVerifierInterface,
} from "../../SecurityMiddleware.sol/IVDFVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "txHash",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "startTime",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IVDFVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IVDFVerifierInterface {
    return new Interface(_abi) as IVDFVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVDFVerifier {
    return new Contract(address, _abi, runner) as unknown as IVDFVerifier;
  }
}
