/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZKVoteVerifier,
  IZKVoteVerifierInterface,
} from "../../SecurityMiddleware.sol/IZKVoteVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "proposalId",
        type: "bytes32",
      },
    ],
    name: "getProposalState",
    outputs: [
      {
        internalType: "uint8",
        name: "commitCount",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "revealCount",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "approvals",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "rejections",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "abstentions",
        type: "uint8",
      },
      {
        internalType: "bool",
        name: "finalized",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZKVoteVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IZKVoteVerifierInterface {
    return new Interface(_abi) as IZKVoteVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IZKVoteVerifier {
    return new Contract(address, _abi, runner) as unknown as IZKVoteVerifier;
  }
}
