/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SecurityMiddlewareInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "GUARDIAN_THRESHOLD"
      | "VDF_DELAY"
      | "blacklistedAddresses"
      | "emergencyPause"
      | "executeTransaction"
      | "frostVerifier"
      | "getTransactionStatus"
      | "getVDFDelay"
      | "isPaused"
      | "pendingTxs"
      | "queueTransaction"
      | "unpause"
      | "vdfVerifier"
      | "zkVoteVerifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GuardianBypass"
      | "MLBotFlagged"
      | "TransactionBlocked"
      | "TransactionExecuted"
      | "TransactionQueued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "GUARDIAN_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "VDF_DELAY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "blacklistedAddresses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "frostVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVDFDelay",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingTxs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "queueTransaction",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      boolean,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "unpause",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vdfVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "zkVoteVerifier",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "GUARDIAN_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "VDF_DELAY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blacklistedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "frostVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVDFDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingTxs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "queueTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vdfVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "zkVoteVerifier",
    data: BytesLike
  ): Result;
}

export namespace GuardianBypassEvent {
  export type InputTuple = [
    txHash: BytesLike,
    proposalId: BytesLike,
    approvals: BigNumberish
  ];
  export type OutputTuple = [
    txHash: string,
    proposalId: string,
    approvals: bigint
  ];
  export interface OutputObject {
    txHash: string;
    proposalId: string;
    approvals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MLBotFlaggedEvent {
  export type InputTuple = [
    txHash: BytesLike,
    suspicionScore: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    txHash: string,
    suspicionScore: bigint,
    reason: string
  ];
  export interface OutputObject {
    txHash: string;
    suspicionScore: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionBlockedEvent {
  export type InputTuple = [txHash: BytesLike, reason: string];
  export type OutputTuple = [txHash: string, reason: string];
  export interface OutputObject {
    txHash: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionExecutedEvent {
  export type InputTuple = [txHash: BytesLike, executionPath: string];
  export type OutputTuple = [txHash: string, executionPath: string];
  export interface OutputObject {
    txHash: string;
    executionPath: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionQueuedEvent {
  export type InputTuple = [
    txHash: BytesLike,
    proposalId: BytesLike,
    mlBotFlagged: boolean,
    vdfDeadline: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    txHash: string,
    proposalId: string,
    mlBotFlagged: boolean,
    vdfDeadline: bigint,
    reason: string
  ];
  export interface OutputObject {
    txHash: string;
    proposalId: string;
    mlBotFlagged: boolean;
    vdfDeadline: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SecurityMiddleware extends BaseContract {
  connect(runner?: ContractRunner | null): SecurityMiddleware;
  waitForDeployment(): Promise<this>;

  interface: SecurityMiddlewareInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  GUARDIAN_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  VDF_DELAY: TypedContractMethod<[], [bigint], "view">;

  blacklistedAddresses: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  emergencyPause: TypedContractMethod<
    [eventId: BytesLike, frostR: BytesLike, frostZ: BytesLike],
    [void],
    "nonpayable"
  >;

  executeTransaction: TypedContractMethod<
    [
      txHash: BytesLike,
      vdfProof: BytesLike,
      frostR: BytesLike,
      frostZ: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  frostVerifier: TypedContractMethod<[], [string], "view">;

  getTransactionStatus: TypedContractMethod<
    [txHash: BytesLike],
    [
      [boolean, boolean, boolean, boolean, boolean, bigint, boolean] & {
        exists: boolean;
        mlBotFlagged: boolean;
        executed: boolean;
        guardianApproved: boolean;
        guardianRejected: boolean;
        vdfDeadline: bigint;
        vdfComplete: boolean;
      }
    ],
    "view"
  >;

  getVDFDelay: TypedContractMethod<[], [bigint], "view">;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  pendingTxs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        bigint,
        bigint,
        string,
        boolean,
        boolean,
        boolean,
        string
      ] & {
        txHash: string;
        sender: string;
        destination: string;
        value: bigint;
        mlBotFlagged: boolean;
        vdfStartTime: bigint;
        vdfDeadline: bigint;
        proposalId: string;
        executed: boolean;
        guardianApproved: boolean;
        guardianRejected: boolean;
        txData: string;
      }
    ],
    "view"
  >;

  queueTransaction: TypedContractMethod<
    [
      txHash: BytesLike,
      sender: AddressLike,
      destination: AddressLike,
      value: BigNumberish,
      mlBotFlagged: boolean,
      txData: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  unpause: TypedContractMethod<
    [eventId: BytesLike, frostR: BytesLike, frostZ: BytesLike],
    [void],
    "nonpayable"
  >;

  vdfVerifier: TypedContractMethod<[], [string], "view">;

  zkVoteVerifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "GUARDIAN_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VDF_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "blacklistedAddresses"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<
    [eventId: BytesLike, frostR: BytesLike, frostZ: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeTransaction"
  ): TypedContractMethod<
    [
      txHash: BytesLike,
      vdfProof: BytesLike,
      frostR: BytesLike,
      frostZ: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "frostVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTransactionStatus"
  ): TypedContractMethod<
    [txHash: BytesLike],
    [
      [boolean, boolean, boolean, boolean, boolean, bigint, boolean] & {
        exists: boolean;
        mlBotFlagged: boolean;
        executed: boolean;
        guardianApproved: boolean;
        guardianRejected: boolean;
        vdfDeadline: bigint;
        vdfComplete: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVDFDelay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingTxs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        bigint,
        bigint,
        string,
        boolean,
        boolean,
        boolean,
        string
      ] & {
        txHash: string;
        sender: string;
        destination: string;
        value: bigint;
        mlBotFlagged: boolean;
        vdfStartTime: bigint;
        vdfDeadline: bigint;
        proposalId: string;
        executed: boolean;
        guardianApproved: boolean;
        guardianRejected: boolean;
        txData: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "queueTransaction"
  ): TypedContractMethod<
    [
      txHash: BytesLike,
      sender: AddressLike,
      destination: AddressLike,
      value: BigNumberish,
      mlBotFlagged: boolean,
      txData: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<
    [eventId: BytesLike, frostR: BytesLike, frostZ: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vdfVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "zkVoteVerifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "GuardianBypass"
  ): TypedContractEvent<
    GuardianBypassEvent.InputTuple,
    GuardianBypassEvent.OutputTuple,
    GuardianBypassEvent.OutputObject
  >;
  getEvent(
    key: "MLBotFlagged"
  ): TypedContractEvent<
    MLBotFlaggedEvent.InputTuple,
    MLBotFlaggedEvent.OutputTuple,
    MLBotFlaggedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionBlocked"
  ): TypedContractEvent<
    TransactionBlockedEvent.InputTuple,
    TransactionBlockedEvent.OutputTuple,
    TransactionBlockedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionExecuted"
  ): TypedContractEvent<
    TransactionExecutedEvent.InputTuple,
    TransactionExecutedEvent.OutputTuple,
    TransactionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionQueued"
  ): TypedContractEvent<
    TransactionQueuedEvent.InputTuple,
    TransactionQueuedEvent.OutputTuple,
    TransactionQueuedEvent.OutputObject
  >;

  filters: {
    "GuardianBypass(bytes32,bytes32,uint8)": TypedContractEvent<
      GuardianBypassEvent.InputTuple,
      GuardianBypassEvent.OutputTuple,
      GuardianBypassEvent.OutputObject
    >;
    GuardianBypass: TypedContractEvent<
      GuardianBypassEvent.InputTuple,
      GuardianBypassEvent.OutputTuple,
      GuardianBypassEvent.OutputObject
    >;

    "MLBotFlagged(bytes32,uint256,string)": TypedContractEvent<
      MLBotFlaggedEvent.InputTuple,
      MLBotFlaggedEvent.OutputTuple,
      MLBotFlaggedEvent.OutputObject
    >;
    MLBotFlagged: TypedContractEvent<
      MLBotFlaggedEvent.InputTuple,
      MLBotFlaggedEvent.OutputTuple,
      MLBotFlaggedEvent.OutputObject
    >;

    "TransactionBlocked(bytes32,string)": TypedContractEvent<
      TransactionBlockedEvent.InputTuple,
      TransactionBlockedEvent.OutputTuple,
      TransactionBlockedEvent.OutputObject
    >;
    TransactionBlocked: TypedContractEvent<
      TransactionBlockedEvent.InputTuple,
      TransactionBlockedEvent.OutputTuple,
      TransactionBlockedEvent.OutputObject
    >;

    "TransactionExecuted(bytes32,string)": TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;
    TransactionExecuted: TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;

    "TransactionQueued(bytes32,bytes32,bool,uint256,string)": TypedContractEvent<
      TransactionQueuedEvent.InputTuple,
      TransactionQueuedEvent.OutputTuple,
      TransactionQueuedEvent.OutputObject
    >;
    TransactionQueued: TypedContractEvent<
      TransactionQueuedEvent.InputTuple,
      TransactionQueuedEvent.OutputTuple,
      TransactionQueuedEvent.OutputObject
    >;
  };
}
